## 如何讓兩個list 相乘

In [7]:
a = [1,3,5,7,9]
b = [2,4,6,8,10]

#traditional
ary = []
for i in range(0,len(a)):
    #print(a[i] * b[i])
    ary.append(a[i] * b[i])
print (ary)

#method 3
print([a[i]*b[i] for i in range(0,len(a))])

#method4
for item in zip(a,b):
    print(item)
    
#method 5
[f*s for f,s in zip(a,b)]

[2, 12, 30, 56, 90]
[2, 12, 30, 56, 90]
(1, 2)
(3, 4)
(5, 6)
(7, 8)
(9, 10)


[2, 12, 30, 56, 90]

In [9]:
import requests
res = requests.get('https://www.104.com.tw/jobbank/custjob/index.php?r=cust&j=623e466f383a426b34363e673c423a1d02d2d2d70463a4e2644j50')
res.encoding = 'utf-8'
print(res.encoding)

utf-8


In [10]:
from bs4 import BeautifulSoup
soup = BeautifulSoup(res.text,'html.parser')
tag = soup.select('dt')
description = soup.select('dd')
for t,d in zip(tag,description):
    print (t.text,d.text.strip())

產業類別： 電腦軟體服務業
產業描述： 資訊軟體
員　　工： 10人
資 本 額： 200萬元
聯 絡 人： 丘先生
公司地址： 台北市中山區南京東路二段地圖
電　　話： 暫不提供
傳　　真： 暫不提供
公司網址： http://www.largitdata.com
相關連結： 更多





商業司登記
Google查公司名稱
求職服務專線 02-2912-6104 轉2
廠商求才專線 


In [17]:
import numpy as np
na = np.array(a)
nb = np.array(b)

nc = na * nb
print (nc)

[ 2 12 30 56 90]


In [22]:
na = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(na)
print(na[0][0])
print(na[:,0])
print(na[0,:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
1
[1 6]
[1 2 3 4 5]


In [25]:
import pandas as pd
df = pd.DataFrame([['frank','M',29],['Mary','F',23],['Tom','M',35],['Ted','M',33],['Jean','F',21]])
df

0  1   2
0  frank  M  29
1   Mary  F  23
2    Tom  M  35
3    Ted  M  33
4   Jean  F  21

In [30]:
df.columns
df.columns = ['name','gender','age']
df
df['age']

0    29
1    23
2    35
3    33
4    21
Name: age, dtype: int64